# Generated by Django 4.0.2 on 2022-04-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_car_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['model']},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['first_name'], 'verbose_name': 'driver', 'verbose_name_plural': 'drivers'},
        ),
    ]
